---
- hosts: all
  become: yes

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest Docker image
      shell: docker pull urmidevops/nginx-webpage:latest

    - name: Remove existing container
      shell: docker rm -f nginx-webpage
      ignore_errors: yes

    - name: Run Docker container
      shell: |
        docker run -d \
          --name nginx-webpage \
          --restart always \
          -p 80:80 \
          urmidevops/nginx-webpage:latest
