---
- hosts: all
  become: yes

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest Docker image
      docker_image:
        name: urmidevops/nginx-webpage
        source: pull
        tag: latest

    - name: Stop existing container
      ignore_errors: yes
      shell: docker rm -f nginx-webpage

    - name: Run Docker container
      shell: |
        docker run -d \
        --name nginx-webpage \
        -p 80:80 \
        --restart always \
        urmidevops/nginx-webpage:latest
